# Team 36: Is income and education influence sentiment?
# city: Melbourne Chongxuan Liang - 1118236    
# city: Melbourne Ruitong Liu - 947759
# city: Melbourne Yuhan Zhao  - 1042775
# city: Beijing Zengxu Zhao  - 978084
# city: Melbourne Zhiqi Liu  - 1071551

---
- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install dependencies
  become: yes
  apt:
    name: ['gcc','unzip','git','xfsprogs','python3-pip','apt-transport-https','ca-certificates','curl','python3-setuptools','software-properties-common','build-essential','python-docker','npm']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Uninstall old versions of docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker', 'docker-engine', 'docker.io']
    state: absent

- name: Add Docker apt repository key
  tags: 'docker'
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update apt cache
  tags: 'docker'
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  tags: 'docker'
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker-compose']
    state: latest
    executable: pip3