# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: demo-vol-1-1
    vol_size: 10
  - vol_name: demo-vol-1-2
    vol_size: 10
  - vol_name: demo-vol-2-1
    vol_size: 10
  - vol_name: demo-vol-2-2
    vol_size: 10

# Security group
security_groups:
  # - name: Test_1_ssh
  #   description: "Demo security group for SSH access"
  #   protocol: tcp
  #   port_range_min: 22
  #   port_range_max: 22
  #   remote_ip_prefix: 0.0.0.0/0
  - name: Test_1
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: demo-1
    volumes: ['demo-vol-1-1', 'demo-vol-1-2']
  - name: demo-2
    volumes: ['demo-vol-2-1', 'demo-vol-2-2']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: lcx_1
instance_flavor: uom.mse.2c9g

cookie: 'cookie'
