
# Team 36: Is income and education influence sentiment?
# city: Melbourne Chongxuan Liang - 1118236    
# city: Melbourne Ruitong Liu - 947759
# city: Melbourne Yuhan Zhao  - 1042775
# city: Beijing Zengxu Zhao  - 978084
# city: Melbourne Zhiqi Liu  - 1071551

# Common vars
availability_zone: melbourne-qh2-uom

# Volume
volumes:
  - vol_name: vol-1
    vol_size: 80
  - vol_name: vol-2
    vol_size: 80
  - vol_name: vol-3
    vol_size: 80
  - vol_name: vol-4
    vol_size: 10

# Security group
security_groups:
  # - name: Test_1_ssh
  #   description: "Demo security group for SSH access"
  #   protocol: tcp
  #   port_range_min: 22
  #   port_range_max: 22
  #   remote_ip_prefix: 0.0.0.0/0
  - name: Test_1
    description: "Demo security group for HTTP"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0

# Instance
instances:
  - name: instance-1
    volumes: ['vol-1']
  - name: instance-2
    volumes: ['vol-2']
  - name: instance-3
    volumes: ['vol-3']
  - name: instance-4
    volumes: ['vol-4']

instance_image: 45225edb-66d8-4fd0-bf41-132a31a18166
instance_key_name: lcx_1
instance_flavor: uom.mse.2c9g

cookie: 'cookie'
num_dbnodes: 3
dbnodes_to_add: [instance-2,instance-3]
