---
- name: Create directory
  become: yes
  file:
    path: '/etc/systemd/system/docker.service.d'
    recurse: yes
    state: directory

- name: add proxy config file
  become: yes
  copy:
    content: "[Service]\nEnvironment=\"HTTP_PROXY=http://wwwproxy.unimelb.edu.au:8000\""
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf

- name: reload daemon
  become: yes
  command: systemctl daemon-reload

- name: restart daemon
  become: yes
  command: systemctl restart docker