- name: Install dependencies
  become: yes
  pip:
    name: ['flask', 'flask-cors', 'couchdb']
    state: latest
    executable: pip3

- name: Install pm2
  become: yes
  npm:
    name: 'pm2'
    global: yes

- name: copy app.py to server
  become: yes
  template:
    src: app.py.j2
    dest: '/home/ubuntu/codes/Backend/run.py'
    owner: ubuntu
    group: ubuntu
    force: no

- name: Start processing data.
  shell: 
    cmd: pm2 start run.py --name backend --interpreter python3
    chdir: /home/ubuntu/codes/Backend

- name: npm install
  become: yes
  npm:
    path: '/home/ubuntu/codes/Frontend'

# For debugging
# - name: Delete existing pm2 process
#   command: pm2 delete all
#   ignore_errors: yes

- name: copy graphs.vue to server
  become: yes
  template:
    src: graphs.vue.j2
    dest: '/home/ubuntu/codes/Frontend/src/views/graphs.vue'
    owner: ubuntu
    group: ubuntu
    force: no

- name: copy map.vue to server
  become: yes
  template:
    src: map.vue.j2
    dest: '/home/ubuntu/codes/Frontend/src/views/map.vue'
    owner: ubuntu
    group: ubuntu
    force: no
    
- name: Start Vue serve
  shell:
    cmd: pm2 start npm -- run serve
    chdir: /home/ubuntu/codes/Frontend