- name: Install dependencies
  become: yes
  pip:
    name: ['flask', 'flask-cors', 'couchdb']
    state: latest
    executable: pip3



- name: npm install
  become: yes
  npm:
    path: '/home/ubuntu/codes/Frontend'