- name: Install dependencies
  become: yes
  pip:
    name: ['flask', 'flask-cors', 'couchdb']
    state: latest
    executable: pip3

- name: Install pm2
  become: yes
  npm:
    name: 'pm2'
    global: yes

- name: npm install
  become: yes
  npm:
    path: '/home/ubuntu/codes/Frontend'

For debugging
- name: Delete existing pm2 process
  command: pm2 delete all
  ignore_errors: yes

- name: Start processing data.
  shell: 
    cmd: pm2 start app.py --name backend --interpreter python3
    chdir: /home/ubuntu/codes/Backend

- name: Start Vue serve
  shell:
    cmd: pm2 start npm -- run serve
    chdir: /home/ubuntu/codes/Frontend