# Team 36: Is income and education influence sentiment?
# city: Melbourne Chongxuan Liang - 1118236    
# city: Melbourne Ruitong Liu - 947759
# city: Melbourne Yuhan Zhao  - 1042775
# city: Beijing Zengxu Zhao  - 978084
# city: Melbourne Zhiqi Liu  - 1071551

---
- name: create config directory for couchdb
  become: yes
  file:
    path: '/home/ubuntu/couchdb/etc/local.d'
    recurse: yes
    state: directory

- name: copy vm.args to instance
  become: yes
  template:
    src: vm.args.j2
    dest: '/home/ubuntu/couchdb/etc/vm.args'
    owner: ubuntu
    group: ubuntu
    force: no

- name: copy docker.ini to instance
  become: yes
  template:
    src: docker.ini
    dest: '/home/ubuntu/couchdb/etc/local.d/docker.ini'
    owner: ubuntu
    group: ubuntu
    force: no

- name: launch couchdb
  become: yes
  become_user: 'root'
  docker_container:
    name: couchdb
    hostname: couchdb
    image: 'couchdb:latest'
    restart_policy: always
    state: started
    env:
      COUCHDB_USER: 'ccc'
      COUCHDB_PASSWORD: '90024'
    published_ports:
      - 5984:5984
      - 4369:4369
      - 9100-9200:9100-9200
    volumes:
      - /home/ubuntu/couchdb/etc/local.d/docker.ini:/opt/couchdb/etc/local.d/docker.ini:rw
      - /home/ubuntu/couchdb/data:/opt/couchdb/data
      - /home/ubuntu/couchdb/etc/vm.args:/opt/couchdb/etc/vm.args:rw
