# Team 36: Is income and education influence sentiment?
# city: Melbourne Chongxuan Liang - 1118236    
# city: Melbourne Ruitong Liu - 947759
# city: Melbourne Yuhan Zhao  - 1042775
# city: Beijing Zengxu Zhao  - 978084
# city: Melbourne Zhiqi Liu  - 1071551

- hosts: localhost
  vars_files:
    - host_vars/var_new_nodes.yaml
  gather_facts: true

  roles:
    - role: Install-dependencies-for-opensdk
    - role: show-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

- hosts: new
  vars_files:
    - host_vars/var_new_nodes.yaml
  gather_facts: true

    - role: add-proxy
    - role: install-environment
    - role: add-proxy-for-docker
    - role: launch-couchdb

- hosts: coordinator
  vars_files:
    - host_vars/var_new_nodes.yaml
  gather_facts: true

  roles:
    - role: cluster-add-node