# Team 36: Is income and education influence sentiment?
# city: Melbourne Chongxuan Liang - 1118236    
# city: Melbourne Ruitong Liu - 947759
# city: Melbourne Yuhan Zhao  - 1042775
# city: Beijing Zengxu Zhao  - 978084
# city: Melbourne Zhiqi Liu  - 1071551

---
- hosts: webServer
  vars_files:
    - host_vars/var.yaml
  gather_facts: true

  roles:
    - role: clone-repo
    - role: launch-website