- hosts: localhost
  vars_files:
    - host_vars/var.yaml
  gather_facts: true

  roles:
    - role: Install-dependencies-for-opensdk
    - role: show-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

# Password
#OWEwNWE0MTNhNWU3YjBj