- hosts: localhost
  vars_files:
    - host_vars/var.yaml
  gather_facts: true

  roles:
    - role: openstack-common
    - role: openstack-images
    - role: openstack-volume
    - role: openstack-security-group
    - role: openstack-instance

#OWEwNWE0MTNhNWU3YjBj