# Team 36: Is income and education influence sentiment?
# city: Melbourne Chongxuan Liang - 1118236    
# city: Melbourne Ruitong Liu - 947759
# city: Melbourne Yuhan Zhao  - 1042775
# city: Beijing Zengxu Zhao  - 978084
# city: Melbourne Zhiqi Liu  - 1071551

---
- name: enable cluster
  uri:
    url: 'http://localhost:5984/_cluster_setup'
    user: ccc
    password: '90024'
    force_basic_auth: yes
    status_code: 201
    method: POST
    body:
      action: enable_cluster
      bind_address: 0.0.0.0
      username: 'ccc'
      password: '90024'
      port: 5984
      node_count: '{{ num_dbnodes }}'
      remote_node: '{{ item }}'
      remote_current_user: 'ccc'
      remote_current_password: '90024'
    body_format: json
    headers:
      Content-Type: application/json
  register: result
  loop: '{{ instances }}'

- name: Add nodes
  uri:
    url: 'http://localhost:5984/_cluster_setup'
    user: ccc
    password: '90024'
    force_basic_auth: yes
    status_code: 201
    method: POST
    body:
      action: add_node
      host: '{{ item }}'
      port: 5984
      username: ccc
      password: '90024'
    body_format: json
    headers:
      Content-Type: application/json
  register: result
  loop: '{{ instances }}'

- name: finish cluster
  uri:
    url: 'http://localhost:5984/_cluster_setup'
    user: ccc
    password: '90024'
    force_basic_auth: yes
    status_code: 201
    method: POST
    body:
      action: finish_cluster
    body_format: json
    headers:
      Content-Type: application/json
  register: result